// This is an autogenerated file from Firebase Studio.

'use server';

/**
 * @fileOverview Compares the recent trend growth of two keywords.
 *
 * - compareTrends - A function that takes two keywords and returns an analysis
 *   of their relative growth over the last 7 days.
 * - CompareTrendsInput - The input type for the compareTrends function.
 * - CompareTrendsOutput - The return type for the compareTrends function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const CompareTrendsInputSchema = z.object({
  keyword1: z.string().describe('The first keyword to compare.'),
  keyword2: z.string().describe('The second keyword to compare.'),
});
export type CompareTrendsInput = z.infer<typeof CompareTrendsInputSchema>;

const CompareTrendsOutputSchema = z.object({
  winner: z
    .string()
    .describe(
      'The keyword that has shown more significant growth in the last 7 days.'
    ),
  analysis: z
    .string()
    .describe(
      'A detailed analysis explaining why the winning keyword grew more, considering factors like news, events, and search volume changes.'
    ),
});
export type CompareTrendsOutput = z.infer<typeof CompareTrendsOutputSchema>;

export async function compareTrends(
  input: CompareTrendsInput
): Promise<CompareTrendsOutput> {
  return compareTrendsFlow(input);
}

const compareTrendsPrompt = ai.definePrompt({
  name: 'compareTrendsPrompt',
  input: {schema: CompareTrendsInputSchema},
  output: {schema: CompareTrendsOutputSchema},
  prompt: `You are a Google Trends expert. Your task is to analyze the search interest of two keywords over the last 7 days and determine which one has shown more significant growth.

Keywords to compare:
1. {{{keyword1}}}
2. {{{keyword2}}}

Analyze news, events, and other publicly available information to provide a concise and insightful explanation for the growth.

- Identify the keyword with the most significant growth (the "winner").
- Provide a brief analysis explaining the potential reasons for the growth of the winning keyword.
- Be objective and base your analysis on plausible factors.
`,
});

const compareTrendsFlow = ai.defineFlow(
  {
    name: 'compareTrendsFlow',
    inputSchema: CompareTrendsInputSchema,
    outputSchema: CompareTrendsOutputSchema,
  },
  async input => {
    const {output} = await compareTrendsPrompt(input);
    return output!;
  }
);
