// This is an autogenerated file from Firebase Studio.

'use server';

/**
 * @fileOverview Provides explanations for trend fluctuations at a specific point in time.
 *
 * - explainTrendFluctuations - A function that takes a keyword and a specific time
 *   and returns an explanation of the trend's behavior at that time.
 * - ExplainTrendFluctuationsInput - The input type for the explainTrendFluctuations function.
 * - ExplainTrendFluctuationsOutput - The return type for the explainTrendFluctuations function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const ExplainTrendFluctuationsInputSchema = z.object({
  keyword: z.string().describe('The keyword to explain the trend for.'),
  time: z.string().describe('The specific time (date) to explain the trend fluctuation for, in ISO format.'),
});
export type ExplainTrendFluctuationsInput = z.infer<
  typeof ExplainTrendFluctuationsInputSchema
>;

const ExplainTrendFluctuationsOutputSchema = z.object({
  explanation: z
    .string()
    .describe(
      'An AI-powered explanation of the factors contributing to the trend\'s behavior at the specified time.'
    ),
});
export type ExplainTrendFluctuationsOutput = z.infer<
  typeof ExplainTrendFluctuationsOutputSchema
>;

export async function explainTrendFluctuations(
  input: ExplainTrendFluctuationsInput
): Promise<ExplainTrendFluctuationsOutput> {
  return explainTrendFluctuationsFlow(input);
}

const explainTrendFluctuationsPrompt = ai.definePrompt({
  name: 'explainTrendFluctuationsPrompt',
  input: {schema: ExplainTrendFluctuationsInputSchema},
  output: {schema: ExplainTrendFluctuationsOutputSchema},
  prompt: `You are an AI assistant that explains fluctuations in Google Trends data for a given keyword at a specific time.
  Analyze available news articles and resources to provide a concise explanation of why the trend is behaving the way it is.
  Keyword: {{{keyword}}}
  Time: {{{time}}}
  Explanation:
  `,
});

const explainTrendFluctuationsFlow = ai.defineFlow(
  {
    name: 'explainTrendFluctuationsFlow',
    inputSchema: ExplainTrendFluctuationsInputSchema,
    outputSchema: ExplainTrendFluctuationsOutputSchema,
  },
  async input => {
    const {output} = await explainTrendFluctuationsPrompt(input);
    return output!;
  }
);
